### PR TITLE
Fix jit free

### PR DESCRIPTION
**Pull request by yjhmelody**
The study free is incorrect

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
@yjhmelody what was the reason you closed this pull request? Seems a good fix to me?

**Comment by yjhmelody** [comment]
@erikdubbelboer  No, it won't work. I want to let the JIT works. 
If we pass jitFlags, it can free the study. But because the `*C.pcre_extra` has inner pointers, after `toHeap`, the memory still leak.

**Comment by yjhmelody** [comment]
golang gc will collect the `extra` bytes, but it contains pointer info.

**Comment by yjhmelody** [comment]
So I fork the repo and refactor the api.

**Pull request closed without merging**
